###Recuperar todas las peliculas
GET http://localhost:1234/movies

###Recuperar pelicula por id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=Action 